pipelines:
    default:
        - step:
            image: luminositylabs/maven:3.6.3_openjdk-11.0.9.1_zulu-alpine-11.43.55
            script:
                - mvn -U -V -s settings.xml -Psonatype-snapshots,sonatype-staging,sonatype-releases dependency:list-repositories
                - mvn -U -V -s settings.xml -Psonatype-snapshots,sonatype-staging,sonatype-releases dependency:tree
                - mvn -U -V -s settings.xml -Psonatype-snapshots,sonatype-staging,sonatype-releases help:active-profiles clean install
                - mvn -U -V -s settings.xml -Psonatype-snapshots,sonatype-staging,sonatype-releases site site:stage